function [fitresult, gof] = BPwrRegressBat2(AvgCurr2, Sec2)
%CREATEFIT(AVGCURR2,SEC2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : AvgCurr2
%      Y Output: Sec2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 28-Jul-2019 16:07:37


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( AvgCurr2, Sec2 );

% Set up fittype and options.
ft = fittype( 'rat11' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [405.4 122813 29.03];
opts.StartPoint = [405.4 122813 29.03];
opts.Upper = [405.4 122813 29.03];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'Battery 2: Flight Time vs. Avgerage Power', ['g(x) = 1.25*f(x)',newline,'      f(x) is the Power Regression Function for Battery 1',newline,'R-Square: 0.413'], 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Avgerage Power (W)', 'Interpreter', 'none' );
ylabel( 'Flight Time (Sec)', 'Interpreter', 'none' );
title('Average Power vs. Flight Time Using Battery 1 Regression',...
    'FontSize',16);
grid on


