function [fitresult, gof] = createFit(AirT, AirP)
%CREATEFIT(AIRT,AIRP)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : AirT
%      Y Output: AirP
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Jul-2019 15:51:21


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( AirT, AirP );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'AirP vs. AirT', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'AirT', 'Interpreter', 'none' );
ylabel( 'AirP', 'Interpreter', 'none' );
grid on


