function [fitresult, gof] = createFit2(Sfive, Efive)
%CREATEFIT2(SFIVE,EFIVE)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : Sfive
%      Y Output: Efive
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Jun-2019 11:07:27


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( Sfive, Efive );

% Set up fittype and options.
ft = fittype( 'poly3' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'Efive vs. Sfive', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Sfive', 'Interpreter', 'none' );
ylabel( 'Efive', 'Interpreter', 'none' );
grid on

gof


