function [fitresult, gof] = BCurrRegress(AvgCurr, Sec)
%CREATEFIT(AVGCURR,SEC)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : AvgCurr
%      Y Output: Sec
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 28-Jul-2019 15:54:59


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( AvgCurr, Sec );

% Set up fittype and options.
ft = fittype( 'rat11' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0];
opts.StartPoint = [0.416799467930787 0.656859890973707 0.628];
opts.Upper = [Inf Inf 10];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'Flight Time vs. Avgerage Current', ['f(x) = (p1*x + p2) / (x + q1)',newline,'       p1 =       324.3',newline,'       p2 =        7203',newline,'       q1 =       2.1554',newline,'R-Square; 0.9441'], 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Avgerage Current (A)', 'Interpreter', 'none' );
ylabel( 'Flight Time (Sec)', 'Interpreter', 'none' );
title('Average Current vs. Flight Time Using Power Regression',...
    'FontSize',16);
grid on


