function [fitresult, gof] = PowerLinear2(AvgPwr2, totPwr2)
%CREATEFITS(AVGPWR,TOTPWR,AVGPWR2,TOTPWR2)
%  Create fits.
%
%  Data for 'untitled fit 1' fit:
%      X Input : AvgPwr
%      Y Output: totPwr
%  Data for 'untitled fit 2' fit:
%      X Input : AvgPwr2
%      Y Output: totPwr2
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 30-Jul-2019 12:41:06

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 2, 1 );
gof = struct( 'sse', cell( 2, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );


%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( AvgPwr2, totPwr2 );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult{2}, gof(2)] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 2' );
h = plot( fitresult{2}, xData, yData );
legend( h, 'Average Power vs. Total Power', ['f(x) = p1*x + p2',newline,'       p1 =     429.3',newline,'       p2 =    73390',newline,'R-Squared: 0.8848'], 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Average Power (W)', 'Interpreter', 'none' );
ylabel( 'Total Power (J)', 'Interpreter', 'none' );
grid on

